export default [
  {
    id: 1,
    name: "Porsche 911",
    seats: "2",
    color: "red",
    fuelType: "Lauda Type",
    vehicleNumber: "3637383",
    rent: "135000",
    wiki: "http://en.wikipedia.org/wiki/Porsche_997",
    img:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Porsche_997_Turbo_-_Flickr_-_Alexandre_Pr%C3%A9vot_%288%29.jpg/280px-Porsche_997_Turbo_-_Flickr_-_Alexandre_Pr%C3%A9vot_%288%29.jpg",
    isBooked: true,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 2,
    name: "Nissan GT-R",
    seats: "2",
    color: "Black",
    fuelType: "Lauda Type",
    vehicleNumber: "4748483",
    rent: "180000",
    wiki: "http://en.wikipedia.org/wiki/Nissan_Gt-r",
    img: "250px-Nissan_GT-R.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 3,
    name: "BMW M3",
    seats: "2",
    color: "Black",
    fuelType: "Lauda Type",
    vehicleNumber: "3637383",
    rent: "250000",
    wiki: "http://en.wikipedia.org/wiki/Bmw_m3",
    img: "250px-BMW_M3_E92.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 4,
    name: "Audi S5",
    seats: "4",
    color: "White",
    fuelType: "Lauda Type",
    vehicleNumber: "4648933",
    rent: "130000",
    wiki: "http://en.wikipedia.org/wiki/Audi_S5#Audi_S5",
    img: "250px-Audi_S5.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 5,
    name: "Audi TT",
    seats: "4",
    color: "Black",
    fuelType: "Lauda Type",
    vehicleNumber: "347856839",
    rent: "190000",
    wiki: "http://en.wikipedia.org/wiki/Audi_TT",
    img: "250px-2007_Audi_TT_Coupe.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
];
