export default [
  {
    id: 1,
    name: "Porsche 911",
    seats: "2",
    color: "White",
    fuelType: "Lauda Type",
    vehicleNumber: "3637383",
    rent: "135000",
    wiki: "http://en.wikipedia.org/wiki/Porsche_997",
    img:
      "//upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Porsche_997_Turbo_-_Flickr_-_Alexandre_Pr%C3%A9vot_%288%29.jpg/280px-Porsche_997_Turbo_-_Flickr_-_Alexandre_Pr%C3%A9vot_%288%29.jpg",
    isBooked: true,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 2,
    name: "Nissan GT-R",
    seats: "2",
    color: "White",
    fuelType: "Lauda Type",
    vehicleNumber: "4748483",
    rent: "180000",
    wiki: "http://en.wikipedia.org/wiki/Nissan_Gt-r",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/2012_Nissan_GT-R_Egoist.jpg/280px-2012_Nissan_GT-R_Egoist.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 3,
    name: "BMW M3",
    seats: "4",
    color: "Golden",
    fuelType: "Lauda Type",
    vehicleNumber: "3637383",
    rent: "250000",
    wiki: "http://en.wikipedia.org/wiki/Bmw_m3",
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f6/2018_BMW_M3_3.0.jpg/280px-2018_BMW_M3_3.0.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 4,
    name: "Audi S5",
    seats: "4",
    color: "Blue",
    fuelType: "Lauda Type",
    vehicleNumber: "4648933",
    rent: "130000",
    wiki: "http://en.wikipedia.org/wiki/Audi_S5#Audi_S5",
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/7/7d/2018_Audi_S5_TFSi_Quattro_Automatic_3.0_Front.jpg/280px-2018_Audi_S5_TFSi_Quattro_Automatic_3.0_Front.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
  {
    id: 5,
    name: "Audi TT",
    seats: "2",
    color: "Blue",
    fuelType: "Lauda Type",
    vehicleNumber: "347856839",
    rent: "190000",
    wiki: "http://en.wikipedia.org/wiki/Audi_TT",
    img: "//upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg/280px-Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg",
    isBooked: false,
    bookingDetails: {
      cusName: "",
      contactDetails: {
        phoneNumber: "",
      },
      fromDate: "",
      toDate: "",
    },
  },
];
